version: '3.8'

services:
  # api
  

  # mongo
  image: mongo
  restart: always
  environment:
    - MONG_INITDB_ROOT_USERNAME: ${MONGO_USERNAME} 
    - MONG_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
  volumes:
    - ./mongo/mongo-data:/data/db
  ports:
    - ${MONGO_LOCAL_PORT}:${MONGO_CONTAINER_PORT}
