version: '3.8'

services:
  # api:
  #   depends_on: mongo

  mongo:
    image: mongo
    restart: ${MONGO_RESTART_POLICY}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME} 
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - ${MONGO_LOCAL_VOLUME}:${MONGO_CONTAINER_VOLUME}
    ports:
      - ${MONGO_LOCAL_PORT}:${MONGO_CONTAINER_PORT}
    profiles:
      - db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME} 
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:${MONGO_LOCAL_PORT}/